name: Lint & Test

on:
    push:
    pull_request:
        types: [opened, synchronize]

jobs:
    lint_test:
        name: Lint & Test
        runs-on: ubuntu-latest
        timeout-minutes: 15
        strategy:
            matrix:
                node-version: [23]

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm run lint

            - name: Test
              run: pnpm test

            - name: Build
              run: pnpm run build
